# .github/workflows/claude.yml
name: Claude PR Summarizer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get PR content
        id: pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pr.data;

      - name: Summarize PR using Claude
        run: |
          echo "${{ steps.pr.outputs.result }}" > pr.json
          python3 .github/scripts/summarize_pr.py pr.json
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
