# .github/workflows/claude.yml
name: Claude SEO & Content Bot

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 3 AM UTC (~8:30 AM IST)

jobs:
  claude-seo-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install anthropic PyGithub

      - name: Run Claude SEO Reviewer
        run: python3 .github/scripts/seo_reviewer.py
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
